- .github/workflows/docs.yml
- src/docs/asciidoc/index.adoc
- src/test/kotlin/com/csbroker/apiserver/controller/ProblemApiControllerTest.kt
close: MSTR-99
N/A
- 문제 API 테스트 및 REST Docs를 추가했습니다.
> MSTR-99 : 문제 API REST Docs 작성

- src/docs/asciidoc/index.adoc
- src/main/kotlin/com/csbroker/apiserver/controller/ProblemController.kt
- src/main/kotlin/com/csbroker/apiserver/repository/ProblemRepositoryCustomImpl.kt
- src/test/kotlin/com/csbroker/apiserver/controller/ProblemApiControllerTest.kt
close: MSTR-109
N/A
- 푼 문제 검색 기능에 따른 docs 수정이 있었으니, 그 부분을 보면서 이해하면 좋을 것 같습니다.
> MSTR-109 : 문제 검색 기능 구체화

- src/main/kotlin/com/csbroker/apiserver/common/auth/AuthToken.kt
- src/main/kotlin/com/csbroker/apiserver/common/auth/LoginUser.kt
- src/main/kotlin/com/csbroker/apiserver/common/auth/LoginUserArgumentResolver.kt
- src/main/kotlin/com/csbroker/apiserver/common/config/security/WebMcvConfig.kt
- src/main/kotlin/com/csbroker/apiserver/controller/UserController.kt
close: MSTR-113
- 의존성 목록
반복 되는 권한 인증을 어노테이션을 통해 간단하게 처리할 수 있도록 기능 추가 및 리팩토링하였습니다.
> MSTR-113 : 권한 인증 기능 리팩토링

- src/docs/asciidoc/index.adoc
- src/main/kotlin/com/csbroker/apiserver/controller/AuthController.kt
- src/main/kotlin/com/csbroker/apiserver/controller/UserController.kt
- src/main/kotlin/com/csbroker/apiserver/dto/UserLoginDto.kt
- src/main/kotlin/com/csbroker/apiserver/dto/UserLoginResponseDto.kt
- src/main/kotlin/com/csbroker/apiserver/dto/UserUpdateRequestDto.kt
- src/main/kotlin/com/csbroker/apiserver/model/User.kt
- src/main/kotlin/com/csbroker/apiserver/service/AuthService.kt
- src/main/kotlin/com/csbroker/apiserver/service/AuthServiceImpl.kt
- src/main/kotlin/com/csbroker/apiserver/service/CustomOAuth2UserService.kt
- src/main/kotlin/com/csbroker/apiserver/service/UserService.kt
- src/main/kotlin/com/csbroker/apiserver/service/UserServiceImpl.kt
- src/test/kotlin/com/csbroker/apiserver/controller/AuthControllerTest.kt
- src/test/kotlin/com/csbroker/apiserver/controller/UserControllerTest.kt
close: MSTR-111, MSTR-112
N/A
유저 단건 조회, 유저 전체 조회, 유저 정보 수정 API 구현을 완료하였고, 그에 따른 Docs를 작성했습니다.
> MSTR-111, MSTR-112 : 유저 조회 및 수정 API 구현 및 Docs 작성

- src/docs/asciidoc/index.adoc
- src/main/kotlin/com/csbroker/apiserver/common/enums/GradingStandardType.kt
- src/main/kotlin/com/csbroker/apiserver/controller/ProblemController.kt
- src/main/kotlin/com/csbroker/apiserver/dto/ProblemDetailResponseDto.kt
- src/main/kotlin/com/csbroker/apiserver/dto/ProblemResponseDto.kt
- src/main/kotlin/com/csbroker/apiserver/model/Choice.kt
- src/main/kotlin/com/csbroker/apiserver/model/GradingStandard.kt
- src/main/kotlin/com/csbroker/apiserver/model/LongProblem.kt
- src/main/kotlin/com/csbroker/apiserver/model/MultipleChoiceProblem.kt
- src/main/kotlin/com/csbroker/apiserver/model/Problem.kt
- src/main/kotlin/com/csbroker/apiserver/model/ShortProblem.kt
- src/main/kotlin/com/csbroker/apiserver/model/Tag.kt
- src/main/kotlin/com/csbroker/apiserver/model/UserAnswer.kt
- src/main/kotlin/com/csbroker/apiserver/model/UserAnswerGradingStandard.kt
- src/main/kotlin/com/csbroker/apiserver/repository/GradingHistoryRepository.kt
- src/main/kotlin/com/csbroker/apiserver/repository/ProblemRepository.kt
- src/main/kotlin/com/csbroker/apiserver/repository/ProblemTagRepository.kt
- src/main/kotlin/com/csbroker/apiserver/repository/TagRepository.kt
- src/main/kotlin/com/csbroker/apiserver/service/ProblemService.kt
- src/main/kotlin/com/csbroker/apiserver/service/ProblemServiceImpl.kt
- src/test/kotlin/com/csbroker/apiserver/controller/ProblemApiControllerTest.kt
close: MSTR-122
- id 변경에 따른 테스트 및 docs 문서 수정
- ErdCloud의 스키마를 반영했습니다.
- id 값 타입의 변경에 따른 테스트를 수정했습니다.
> MSTR-122 : 백오피스를 위한 db모델 구현

- src/main/kotlin/com/csbroker/apiserver/controller/AdminController.kt
- src/main/kotlin/com/csbroker/apiserver/dto/UpsertSuccessResponseDto.kt
- src/main/kotlin/com/csbroker/apiserver/dto/problem/LongProblemUpsertRequestDto.kt
- src/main/kotlin/com/csbroker/apiserver/dto/problem/MultipleChoiceProblemUpsertRequestDto.kt
- src/main/kotlin/com/csbroker/apiserver/dto/problem/ShortProblemUpsertRequestDto.kt
- src/main/kotlin/com/csbroker/apiserver/model/LongProblem.kt
- src/main/kotlin/com/csbroker/apiserver/model/MultipleChoiceProblem.kt
- src/main/kotlin/com/csbroker/apiserver/model/ShortProblem.kt
- src/main/kotlin/com/csbroker/apiserver/repository/ChoiceRepository.kt
- src/main/kotlin/com/csbroker/apiserver/repository/GradingStandardRepository.kt
- src/main/kotlin/com/csbroker/apiserver/service/ProblemService.kt
- src/main/kotlin/com/csbroker/apiserver/service/ProblemServiceImpl.kt
close: MSTR-133
N/A
- 문제 수정 API를 구현하였습니다.
> MSTR-133 : 문제 수정 API 개발

- src/main/kotlin/com/csbroker/apiserver/common/handler/OAuth2AuthenticationSuccessHandler.kt
- src/main/kotlin/com/csbroker/apiserver/common/util/CookieUtil.kt
- src/main/kotlin/com/csbroker/apiserver/controller/AuthController.kt
- src/main/kotlin/com/csbroker/apiserver/repository/OAuth2AuthorizationRequestBasedOnCookieRepository.kt
close: MSTR-159
- 쿠키가 브라우저 정책에 의해 제대로 세팅되지 않는 문제 해결
- 쿠키 만료 시간을 잘못지정하였던 문제 수정
N/A
- 쿠키의 설정 및 만료시간 설정만 간단하게 고쳤습니다.
- backend-config 레포의 비밀값들을 변경했습니다.
> MSTR-159 : 쿠키 문제 해결

- src/docs/asciidoc/index.adoc
- src/main/kotlin/com/csbroker/apiserver/controller/ProblemController.kt
- src/main/kotlin/com/csbroker/apiserver/dto/problem/ProblemSearchDto.kt
- src/main/kotlin/com/csbroker/apiserver/model/LongProblem.kt
- src/main/kotlin/com/csbroker/apiserver/model/MultipleChoiceProblem.kt
- src/main/kotlin/com/csbroker/apiserver/model/Problem.kt
- src/main/kotlin/com/csbroker/apiserver/model/ShortProblem.kt
- src/main/kotlin/com/csbroker/apiserver/repository/ProblemRepositoryCustomImpl.kt
- src/test/kotlin/com/csbroker/apiserver/controller/ProblemApiControllerTest.kt
close: MSTR-178
N/A
간단하게 type, isGradable query parameter를 추가하여, type 별 조회와 채점 가능 여부에 따라 검색을 할 수 있도록 수정하였습니다.
isGradable이 추후에 다른 문제에도 사용 될 가능성이 높다 판단하여, problem abstract class로 컬럼을 옮기고 공통으로 사용할 수 있게 변경하였습니다.
> MSTR-178 : 문제 검색 API 개선

- src/main/kotlin/com/csbroker/apiserver/dto/problem/LongProblemResponseDto.kt
- src/main/kotlin/com/csbroker/apiserver/dto/problem/LongProblemUpsertRequestDto.kt
- src/main/kotlin/com/csbroker/apiserver/dto/problem/MultipleChoiceProblemUpsertRequestDto.kt
- src/main/kotlin/com/csbroker/apiserver/dto/problem/MultipleProblemResponseDto.kt
- src/main/kotlin/com/csbroker/apiserver/dto/problem/ShortProblemResponseDto.kt
- src/main/kotlin/com/csbroker/apiserver/dto/problem/ShortProblemUpsertRequestDto.kt
- src/main/kotlin/com/csbroker/apiserver/model/LongProblem.kt
- src/main/kotlin/com/csbroker/apiserver/model/MultipleChoiceProblem.kt
- src/main/kotlin/com/csbroker/apiserver/model/ShortProblem.kt
- src/test/kotlin/com/csbroker/apiserver/controller/AdminControllerTest.kt
close: MSTR-160
채점 가능 및 활성화 여부 수정 필드 추가
N/A
- isGradable, isActive를 수정 가능하도록 변경하였습니다.
- isGradable과 isActive가 단건 조회시 response되도록 수정하였습니다.
- 그에 따른 docs와 test code 수정이 있었습니다.
> MSTR-160 : 채점 가능 및 활성화 여부 수정 필드 추가

- build.gradle.kts
- src/test/kotlin/com/csbroker/apiserver/e2e/AdminControllerTest.kt
- src/test/kotlin/com/csbroker/apiserver/e2e/AuthControllerTest.kt
- src/test/kotlin/com/csbroker/apiserver/e2e/ProblemApiControllerTest.kt
- src/test/kotlin/com/csbroker/apiserver/e2e/UserControllerTest.kt
- src/test/kotlin/com/csbroker/apiserver/unit/service/AuthServiceTest.kt
- src/test/kotlin/com/csbroker/apiserver/unit/service/CustomUserDetailsServiceTest.kt
- src/test/kotlin/com/csbroker/apiserver/unit/service/UserServiceTest.kt
close: MSTR-180
- Jacoco : coverage check를 위한 라이브러리
- Mockk  : kotlin mocking 라이브러리
- e2e, unit 테스트 패키지를 분리하였습니다.
- 유저 관련 서비스들에 대한 유닛 테스트를 추가하였습니다.
> MSTR-180 : 유저 관련 유닛 테스트 추가

- src/main/kotlin/com/csbroker/apiserver/controller/ProblemController.kt
- src/main/kotlin/com/csbroker/apiserver/dto/problem/ProblemPageResponseDto.kt
- src/main/kotlin/com/csbroker/apiserver/repository/ProblemRepositoryCustom.kt
- src/main/kotlin/com/csbroker/apiserver/repository/ProblemRepositoryCustomImpl.kt
- src/main/kotlin/com/csbroker/apiserver/service/ProblemService.kt
- src/main/kotlin/com/csbroker/apiserver/service/ProblemServiceImpl.kt
- src/test/kotlin/com/csbroker/apiserver/e2e/ProblemApiControllerTest.kt
close: MSTR-208
N/A
totalPages, totalElements, numberOfElements, size 등의 값을 추가로 응답하도록 설정하였습니다~
> MSTR-208 : Pagination을 위한 응답 데이터 포맷 변경

- .gitignore
- build.gradle.kts
- src/main/kotlin/com/csbroker/apiserver/auth/AuthToken.kt
- src/main/kotlin/com/csbroker/apiserver/common/handler/GlobalExceptionHandler.kt
- src/main/kotlin/com/csbroker/apiserver/service/CustomOAuth2UserService.kt
close: MSTR-229
- 의존성 목록
-  Sentry 추가
- Exception을 추적하기 위한 sentry를 추가했습니다. 추가한 sentry는 대시보드 및 이메일 알림을 설정해놓아, 문제가 발생했을시에 대처가 가능하도록 하였습니다.
> MSTR-229 : Add Sentry

- .github/workflows/deploy-dev.yml
- .github/workflows/deploy-prod.yml
close: MSTR-215
N/A
- 배포 성공 혹은 실패시 알림이 오도록 기능을 추가했습니다.
> MSTR-215 : 배포알림 추가

- src/main/kotlin/com/csbroker/apiserver/dto/user/UserResponseDto.kt
- src/main/kotlin/com/csbroker/apiserver/dto/user/UserUpdateRequestDto.kt
- src/main/kotlin/com/csbroker/apiserver/model/User.kt
- src/test/kotlin/com/csbroker/apiserver/e2e/UserControllerTest.kt
close: MSTR-234, MSTR-235
N/A
- 추가하기로 한 데이터 ( major, job, techs, githubUrl, linkedinUrl ) 에 따라, db 스키마, 응답스펙, 테스트를 수정했습니다.
> MSTR-235 : 유저 정보 추가에 따른 API 수정

- src/docs/asciidoc/index.adoc
- src/main/kotlin/com/csbroker/apiserver/controller/UserController.kt
- src/main/kotlin/com/csbroker/apiserver/dto/user/UserStatsDto.kt
- src/main/kotlin/com/csbroker/apiserver/model/LongProblem.kt
- src/main/kotlin/com/csbroker/apiserver/model/MultipleChoiceProblem.kt
- src/main/kotlin/com/csbroker/apiserver/model/Problem.kt
- src/main/kotlin/com/csbroker/apiserver/model/ShortProblem.kt
- src/main/kotlin/com/csbroker/apiserver/model/User.kt
- src/main/kotlin/com/csbroker/apiserver/repository/GradingHistoryRepository.kt
- src/main/kotlin/com/csbroker/apiserver/service/UserService.kt
- src/main/kotlin/com/csbroker/apiserver/service/UserServiceImpl.kt
- src/test/kotlin/com/csbroker/apiserver/e2e/UserControllerTest.kt
- src/test/kotlin/com/csbroker/apiserver/unit/service/UserServiceTest.kt
close: MSTR-245
N/A
- 유저 통계 API를 구현하였습니다.
- API 추가에 따른 문서를 업데이트하였고, merge conflict가 발생해서 부랴부랴 수정했습니다.
- user service impl 의 함수에서 오류가 없는지 봐주세요!
> MSTR-245 : 유저 통계 API 구현

- src/main/kotlin/com/csbroker/apiserver/dto/user/UserResponseDto.kt
- src/main/kotlin/com/csbroker/apiserver/dto/user/UserUpdateRequestDto.kt
- src/main/kotlin/com/csbroker/apiserver/model/User.kt
- src/test/kotlin/com/csbroker/apiserver/e2e/UserControllerTest.kt
close: MSTR-256
유저 정보 희망 직무 필드 추가
N/A
- 간단하게 job objective 필드만 추가했습니다~
> MSTR-256 : 유저 정보 희망 직무 필드 추가

- src/docs/asciidoc/index.adoc
- src/main/kotlin/com/csbroker/apiserver/controller/AdminController.kt
- src/main/kotlin/com/csbroker/apiserver/dto/useranswer/AssignUserAnswerDto.kt
- src/main/kotlin/com/csbroker/apiserver/repository/UserAnswerRepository.kt
- src/main/kotlin/com/csbroker/apiserver/service/SesMailServiceImpl.kt
- src/main/kotlin/com/csbroker/apiserver/service/UserAnswerService.kt
- src/main/kotlin/com/csbroker/apiserver/service/UserAnswerServiceImpl.kt
- src/test/kotlin/com/csbroker/apiserver/e2e/AdminControllerTest.kt
close: MSTR-263
- 의존성 목록
- AWS SES 를 사용하는 service 코드에 인증 코드가 redis에 적재되도록하는 코드를 빼먹은 것을 찾아서.. 핫픽스했습니다.
- 유저 응답 라벨링 및 검수를 위한 api를 구현하였습니다.
> MSTR-263 : 라벨링 및 검수자 할당 API 구현

- src/docs/asciidoc/index.adoc
- src/main/kotlin/com/csbroker/apiserver/controller/CommonController.kt
- src/main/kotlin/com/csbroker/apiserver/model/Tech.kt
- src/main/kotlin/com/csbroker/apiserver/repository/TechRepository.kt
- src/main/kotlin/com/csbroker/apiserver/service/CommonService.kt
- src/main/kotlin/com/csbroker/apiserver/service/CommonServiceImpl.kt
- src/test/kotlin/com/csbroker/apiserver/e2e/CommonControllerTest.kt
close: MSTR-284
- N/A
- DB에 저장되어 있는 기술 데이터를 검색할 수 있는 간단한 API를 구현하였습니다.
> MSTR-284 : 유저 프로필에 사용되는 기술 검색 API 구현

- build.gradle.kts
- src/main/kotlin/com/csbroker/apiserver/common/filter/LoggingFilter.kt
- src/main/kotlin/com/csbroker/apiserver/controller/CommonController.kt
- src/main/kotlin/com/csbroker/apiserver/dto/user/UserResponseDto.kt
- src/main/kotlin/com/csbroker/apiserver/model/User.kt
- src/main/kotlin/com/csbroker/apiserver/service/S3Service.kt
- src/main/kotlin/com/csbroker/apiserver/service/S3ServiceImpl.kt
- src/main/kotlin/com/csbroker/apiserver/service/UserService.kt
- src/main/kotlin/com/csbroker/apiserver/service/UserServiceImpl.kt
- src/test/kotlin/com/csbroker/apiserver/e2e/UserControllerTest.kt
close: MSTR-285
- 의존성 목록
- S3 버킷에 이미지를 업로드하고, 그 이미지를 유저 디비에 넣도록 했습니다.
- upload는 logging에서 일단 뺐습니다. 로깅할 때 데이터를 보통 logging하는데, 이 때 읽어버리면 controller에서 못쓰더라구요,.
> MSTR-285 : 이미지 업로드 api 구현

- src/main/kotlin/com/csbroker/apiserver/ApiServerApplication.kt
- src/main/kotlin/com/csbroker/apiserver/dto/user/RankResultDto.kt
- src/main/kotlin/com/csbroker/apiserver/dto/user/UserStatsDto.kt
- src/main/kotlin/com/csbroker/apiserver/repository/common/RedisRepository.kt
- src/main/kotlin/com/csbroker/apiserver/service/UserService.kt
- src/main/kotlin/com/csbroker/apiserver/service/UserServiceImpl.kt
- src/test/kotlin/com/csbroker/apiserver/e2e/UserControllerTest.kt
- src/test/kotlin/com/csbroker/apiserver/unit/service/UserServiceTest.kt
close: MSTR-286
- 의존성 목록
- feat/285 브랜치에서부터 따버려서, implement rank system 커밋부터 보시면 됩니다.
> MSTR-286 : 랭킹 구현

- src/main/kotlin/com/csbroker/apiserver/controller/ProblemController.kt
- src/main/kotlin/com/csbroker/apiserver/dto/problem/GradingHistoryStats.kt
- src/main/kotlin/com/csbroker/apiserver/dto/problem/ProblemCommonDetailResponse.kt
- src/main/kotlin/com/csbroker/apiserver/dto/problem/ProblemResponseDto.kt
- src/main/kotlin/com/csbroker/apiserver/dto/problem/ProblemSearchDto.kt
- src/main/kotlin/com/csbroker/apiserver/dto/problem/grade/GradingRequestDto.kt
- src/main/kotlin/com/csbroker/apiserver/dto/problem/grade/GradingResponseDto.kt
- src/main/kotlin/com/csbroker/apiserver/dto/problem/longproblem/LongProblemDetailResponseDto.kt
- src/main/kotlin/com/csbroker/apiserver/dto/problem/longproblem/LongProblemGradingHistoryDto.kt
- src/main/kotlin/com/csbroker/apiserver/dto/problem/multiplechoiceproblem/MultipleChoiceProblemDetailResponseDto.kt
- src/main/kotlin/com/csbroker/apiserver/dto/problem/multiplechoiceproblem/MultipleChoiceProblemGradingHistoryDto.kt
- src/main/kotlin/com/csbroker/apiserver/dto/problem/shortproblem/ShortProblemDetailResponseDto.kt
- src/main/kotlin/com/csbroker/apiserver/dto/problem/shortproblem/ShortProblemGradingHistoryDto.kt
- src/main/kotlin/com/csbroker/apiserver/model/LongProblem.kt
- src/main/kotlin/com/csbroker/apiserver/model/MultipleChoiceProblem.kt
- src/main/kotlin/com/csbroker/apiserver/model/ShortProblem.kt
- src/main/kotlin/com/csbroker/apiserver/repository/ProblemRepositoryCustomImpl.kt
- src/main/kotlin/com/csbroker/apiserver/service/ProblemService.kt
- src/main/kotlin/com/csbroker/apiserver/service/ProblemServiceImpl.kt
- src/test/kotlin/com/csbroker/apiserver/e2e/ProblemApiControllerTest.kt
close: MSTR-289
- 의존성 목록
- 288에 의존적인 commit이라 MSTR-288이 approve 되면, 같이 merge 예정입니다.
> MSTR-289 : 문제 통계 값 변경

- src/docs/asciidoc/index.adoc
- src/main/kotlin/com/csbroker/apiserver/controller/CommonController.kt
- src/main/kotlin/com/csbroker/apiserver/controller/UserController.kt
- src/main/kotlin/com/csbroker/apiserver/dto/common/RankListDto.kt
- src/main/kotlin/com/csbroker/apiserver/model/UserAnswer.kt
- src/main/kotlin/com/csbroker/apiserver/repository/common/RedisRepository.kt
- src/main/kotlin/com/csbroker/apiserver/service/AuthServiceImpl.kt
- src/main/kotlin/com/csbroker/apiserver/service/CommonService.kt
- src/main/kotlin/com/csbroker/apiserver/service/CommonServiceImpl.kt
- src/main/kotlin/com/csbroker/apiserver/service/CustomOAuth2UserService.kt
- src/main/kotlin/com/csbroker/apiserver/service/ProblemServiceImpl.kt
- src/main/kotlin/com/csbroker/apiserver/service/UserService.kt
- src/main/kotlin/com/csbroker/apiserver/service/UserServiceImpl.kt
- src/test/kotlin/com/csbroker/apiserver/e2e/CommonControllerTest.kt
- src/test/kotlin/com/csbroker/apiserver/e2e/UserControllerTest.kt
- src/test/kotlin/com/csbroker/apiserver/unit/service/AuthServiceTest.kt
close: MSTR-304
N/A
- 랭킹 리스트 구현을 완료했습니다. 그에 따라, 테스트와 문서화하였습니다.
- 기타 버그를 수정했습니다.
> MSTR-304 : 랭킹 리스트 구현

- src/main/kotlin/io/csbroker/apiserver/common/client/AIServerClient.kt
- src/main/kotlin/io/csbroker/apiserver/dto/problem/grade/GradeResultDto.kt
- src/main/kotlin/io/csbroker/apiserver/dto/problem/grade/KeywordGradingRequestDto.kt
- src/main/kotlin/io/csbroker/apiserver/dto/problem/grade/KeywordGradingResponseDto.kt
- src/main/kotlin/io/csbroker/apiserver/service/ProblemServiceImpl.kt
- src/main/kotlin/io/csbroker/apiserver/service/S3ServiceImpl.kt
- src/main/kotlin/io/csbroker/apiserver/service/SesMailServiceImpl.kt
close: N/A
- 의존성 목록
- N/A
- 채점 가능여부에 따라, 각 요청을 분리했습니다.
- 필요없는 spring mail 정보를 제거하였습니다.
> Hotfix - problem grade

- src/main/kotlin/io/csbroker/apiserver/dto/problem/longproblem/LongProblemDetailResponseDto.kt
- src/main/kotlin/io/csbroker/apiserver/dto/problem/multiplechoiceproblem/MultipleChoiceProblemDetailResponseDto.kt
- src/main/kotlin/io/csbroker/apiserver/model/LongProblem.kt
- src/main/kotlin/io/csbroker/apiserver/model/MultipleChoiceProblem.kt
- src/test/kotlin/io/csbroker/apiserver/e2e/ProblemApiControllerTest.kt
close: MSTR-341, MSTR-342
N/A
-  간단한 수정이라 특이한 점은 없습니다~
> MSTR-341, MSTR-342 : 문제 내용 상세에 필드 ( 채점 가능 여부, 다중 답안 여부 ) 추가

- src/main/kotlin/io/csbroker/apiserver/service/UserServiceImpl.kt
remove cacheable
close: X
- 의존성 목록
> :ambulance: Remove cacheable

- src/main/kotlin/io/csbroker/apiserver/service/UserServiceImpl.kt
close: #
- 의존성 목록
- 특이 사항 1
- 특이 사항 2
> [prod] remove cacheable 

- src/main/kotlin/io/csbroker/apiserver/model/LongProblem.kt
close: MSTR-361
- N/A
- merge 전에 아래 DDL을 실행해주세요. ( dev, prod  모두 )
```SQL
ALTER TABLE long_problem MODIFY standard_answer LONGTEXT NOT NULL;
```
> MSTR-361 : 모범답안 사이즈 수정

- src/docs/asciidoc/index.adoc
- src/main/kotlin/io/csbroker/apiserver/controller/ProblemController.kt
- src/main/kotlin/io/csbroker/apiserver/service/ProblemService.kt
- src/main/kotlin/io/csbroker/apiserver/service/ProblemServiceImpl.kt
- src/test/kotlin/io/csbroker/apiserver/e2e/ProblemApiControllerTest.kt
close: MSTR-370
N/A
- @Kim-Hyunjo isGrading의 기본 값은 true 입니다. ( 아무것도 안보내면, 그냥 AI 서버 찌름 )
> MSTR-370 : 실제 채점을 진행하는지 여부를 체크하는 request parameter 추가

- src/main/kotlin/io/csbroker/apiserver/common/util/CookieUtil.kt
- src/main/kotlin/io/csbroker/apiserver/common/util/HeaderUtil.kt
- src/main/kotlin/io/csbroker/apiserver/controller/v2/response/ShortProblemDetailResponseV2Dto.kt
- src/main/kotlin/io/csbroker/apiserver/dto/problem/longproblem/LongProblemDetailResponseDto.kt
- src/main/kotlin/io/csbroker/apiserver/dto/problem/multiplechoiceproblem/MultipleChoiceProblemDetailResponseDto.kt
- src/main/kotlin/io/csbroker/apiserver/dto/problem/shortproblem/ShortProblemDetailResponseDto.kt
- src/main/kotlin/io/csbroker/apiserver/model/LongProblem.kt
- src/main/kotlin/io/csbroker/apiserver/model/MultipleChoiceProblem.kt
- src/main/kotlin/io/csbroker/apiserver/model/ShortProblem.kt
- src/test/kotlin/io/csbroker/apiserver/e2e/AdminControllerTest.kt
- src/test/kotlin/io/csbroker/apiserver/e2e/AuthControllerTest.kt
- src/test/kotlin/io/csbroker/apiserver/e2e/NotificationControllerTest.kt
- src/test/kotlin/io/csbroker/apiserver/e2e/ProblemApiControllerTest.kt
- src/test/kotlin/io/csbroker/apiserver/e2e/ProblemControllerV2Test.kt
close: N/A
문제 단일 조회 응답에 배점 정보를 추가
- 메일 테스트가 실제로 메일이 나가고 있어서 그것을 제거 -> 추후 mock을 적용하여 추가 예정
> feat : 문제 단일 조회 응답에 배점 정보를 추가

- build.gradle.kts
- src/docs/asciidoc/index.adoc
- src/main/kotlin/io/csbroker/apiserver/controller/v2/ProblemControllerV2.kt
- src/main/kotlin/io/csbroker/apiserver/controller/v2/request/ChallengeCreateRequest.kt
- src/main/kotlin/io/csbroker/apiserver/dto/problem/challenge/CreateChallengeDto.kt
- src/main/kotlin/io/csbroker/apiserver/model/Challenge.kt
- src/main/kotlin/io/csbroker/apiserver/repository/ChallengeRepository.kt
- src/main/kotlin/io/csbroker/apiserver/service/ProblemService.kt
- src/main/kotlin/io/csbroker/apiserver/service/ProblemServiceImpl.kt
- src/test/kotlin/io/csbroker/apiserver/e2e/ProblemControllerV2Test.kt
close: #MSTR-365
- 의존성 목록
- spring-boot-starter-validation 추가
- 슬랙 알림 보내는건 천천히 해보겠습니다. 일단 redash로 대체해도 될 듯.
> [MSTR-365] feat : 문제 이의 제기 추가

- src/main/kotlin/io/csbroker/apiserver/common/filter/LoggingFilter.kt
> hotfix : fix logging

- src/main/kotlin/io/csbroker/apiserver/auth/LoginUserArgumentResolver.kt
> hotfix : fix auth

- src/main/kotlin/io/csbroker/apiserver/dto/problem/longproblem/LongProblemGradingHistoryDto.kt
- src/main/kotlin/io/csbroker/apiserver/model/StandardAnswer.kt
- src/main/kotlin/io/csbroker/apiserver/repository/StandardAnswerRepository.kt
- src/main/kotlin/io/csbroker/apiserver/service/ProblemServiceImpl.kt
close: N/A
- 의존성 목록 : N/A
- Admin에서 답안을 추가할 수 있는 API를 추후 만들어 보겠음.
> feat : 서술형 모범 답안을 여러개로 변경

- src/main/kotlin/io/csbroker/apiserver/common/client/OpenAiClient.kt
- src/main/kotlin/io/csbroker/apiserver/common/client/request/ChatRequestDto.kt
- src/main/kotlin/io/csbroker/apiserver/common/client/response/ChatResponseDto.kt
- src/main/kotlin/io/csbroker/apiserver/common/config/security/WebMcvConfig.kt
- src/main/kotlin/io/csbroker/apiserver/common/interceptor/HttpInterceptor.kt
- src/main/kotlin/io/csbroker/apiserver/common/interceptor/ratelimit/ApiPathBasedRateLimiter.kt
- src/main/kotlin/io/csbroker/apiserver/common/interceptor/ratelimit/BaseRateLimiter.kt
- src/main/kotlin/io/csbroker/apiserver/common/interceptor/ratelimit/RateLimiter.kt
- src/main/kotlin/io/csbroker/apiserver/controller/v1/CommonController.kt
- src/main/kotlin/io/csbroker/apiserver/dto/common/ChatCompletionRequestDto.kt
- src/main/kotlin/io/csbroker/apiserver/model/ChatResult.kt
- src/main/kotlin/io/csbroker/apiserver/repository/ChatResultRepository.kt
- src/main/kotlin/io/csbroker/apiserver/service/ChatService.kt
- src/main/kotlin/io/csbroker/apiserver/service/ChatServiceImpl.kt
close: N/A
- 의존성 목록 : N/A
- 뭔가 Rate Limiter 잘 짠거 같음 ㅋㅋ.
> feat : ChatGPT 연동 API 추가

- .github/workflows/docs.yml
- .github/workflows/test.yml
- build.gradle.kts
- src/docs/asciidoc/index.adoc
- src/main/kotlin/io/csbroker/apiserver/controller/v1/AdminController.kt
- src/test/kotlin/io/csbroker/apiserver/e2e/AdminControllerMockTest.kt
- src/test/kotlin/io/csbroker/apiserver/e2e/ProblemSetControllerTest.kt
- src/test/kotlin/io/csbroker/apiserver/e2e/RestDocsTest.kt
close: N/A
- 의존성 목록
- org.springframework.restdocs:spring-restdocs-restassured
- io.rest-assured:spring-mock-mvc
- 여태까지 문서화에 사용되던 테스트 방식이 너무 느려서, 변경했습니다.
> docs: 문제 세트 API 문서화

- src/main/kotlin/io/csbroker/apiserver/model/Problem.kt
- src/main/kotlin/io/csbroker/apiserver/model/ProblemSet.kt
close: # N/A
- 의존성 목록 : N/A
- @Kim-Hyunjo 님이 제보해주신 버그 수정입니다.
> fix : 문제 세트에 속하는 문제 개수를 가져오지 못하던 버그 수정

- src/main/kotlin/io/csbroker/apiserver/controller/v1/admin/problem/AdminProblemController.kt
- src/main/kotlin/io/csbroker/apiserver/controller/v1/admin/problem/AdminProblemSetController.kt
- src/main/kotlin/io/csbroker/apiserver/controller/v1/problem/LongProblemController.kt
- src/main/kotlin/io/csbroker/apiserver/controller/v1/problem/MultipleProblemController.kt
- src/main/kotlin/io/csbroker/apiserver/controller/v1/problem/ShortProblemController.kt
- src/main/kotlin/io/csbroker/apiserver/dto/problem/AdminProblemResponseDto.kt
- src/main/kotlin/io/csbroker/apiserver/dto/problem/AdminProblemSearchResponseDto.kt
- src/main/kotlin/io/csbroker/apiserver/dto/problem/AdminUpsertRequestDto.kt
- src/main/kotlin/io/csbroker/apiserver/dto/problem/ProblemDetailResponseDto.kt
- src/main/kotlin/io/csbroker/apiserver/dto/problem/ProblemGradingHistoryDto.kt
- src/main/kotlin/io/csbroker/apiserver/dto/problem/longproblem/LongProblemDetailResponseDto.kt
- src/main/kotlin/io/csbroker/apiserver/dto/problem/longproblem/LongProblemGradingHistoryDto.kt
- src/main/kotlin/io/csbroker/apiserver/dto/problem/longproblem/LongProblemResponseDto.kt
- src/main/kotlin/io/csbroker/apiserver/dto/problem/longproblem/LongProblemSearchResponseDto.kt
- src/main/kotlin/io/csbroker/apiserver/dto/problem/longproblem/LongProblemUpsertRequestDto.kt
- src/main/kotlin/io/csbroker/apiserver/dto/problem/multiplechoiceproblem/MultipleChoiceProblemDetailResponseDto.kt
- src/main/kotlin/io/csbroker/apiserver/dto/problem/multiplechoiceproblem/MultipleChoiceProblemGradingHistoryDto.kt
- src/main/kotlin/io/csbroker/apiserver/dto/problem/multiplechoiceproblem/MultipleChoiceProblemResponseDto.kt
- src/main/kotlin/io/csbroker/apiserver/dto/problem/multiplechoiceproblem/MultipleChoiceProblemSearchResponseDto.kt
- src/main/kotlin/io/csbroker/apiserver/dto/problem/multiplechoiceproblem/MultipleChoiceProblemUpsertRequestDto.kt
- src/main/kotlin/io/csbroker/apiserver/dto/problem/shortproblem/ShortProblemDetailResponseDto.kt
- src/main/kotlin/io/csbroker/apiserver/dto/problem/shortproblem/ShortProblemGradingHistoryDto.kt
- src/main/kotlin/io/csbroker/apiserver/dto/problem/shortproblem/ShortProblemResponseDto.kt
- src/main/kotlin/io/csbroker/apiserver/dto/problem/shortproblem/ShortProblemSearchResponseDto.kt
- src/main/kotlin/io/csbroker/apiserver/dto/problem/shortproblem/ShortProblemUpsertRequestDto.kt
- src/test/kotlin/io/csbroker/apiserver/controller/v1/admin/problem/AdminProblemControllerTest.kt
- src/test/kotlin/io/csbroker/apiserver/controller/v1/admin/problem/AdminProblemSetControllerTest.kt
close: MSTR-412
MultipleProblem, MultipleChoiceProblem이 혼용되어 있어서 통일해야 하는데 거기는 entity까지 엮여있어서 안 건들였어요..
> MSTR-407 : [BE] 리팩토링

- build.gradle.kts
- src/main/kotlin/io/csbroker/apiserver/common/config/security/SecurityConfig.kt
- src/main/kotlin/io/csbroker/apiserver/service/auth/AuthServiceImpl.kt
- src/main/kotlin/io/csbroker/apiserver/service/user/UserServiceImpl.kt
- src/test/kotlin/io/csbroker/apiserver/controller/v1/admin/problem/AdminProblemControllerTest.kt
- src/test/kotlin/io/csbroker/apiserver/controller/v1/admin/problem/AdminUserAnswerProblemControllerTest.kt
- src/test/kotlin/io/csbroker/apiserver/controller/v1/common/AuthControllerTest.kt
- src/test/kotlin/io/csbroker/apiserver/controller/v1/common/NotificationControllerTest.kt
- src/test/kotlin/io/csbroker/apiserver/controller/v2/problem/ProblemControllerV2Test.kt
- src/test/kotlin/io/csbroker/apiserver/service/AuthServiceTest.kt
- src/test/kotlin/io/csbroker/apiserver/service/CustomUserDetailsServiceTest.kt
- src/test/kotlin/io/csbroker/apiserver/service/UserServiceTest.kt
close: # N/A
- 의존성 목록
- mockk 1.9.3 -> 1.13.4
- `every { block() } returns Unit` 으로 사용하던 것을 `justRun { block() }` 으로 수정
- 한 테스트 클래스에서 mock 처리한 클래스를 테스트 함수에서 재사용하던 것을 각 테스트마다 초기화하도록 수정
> refactor : test

- src/main/kotlin/io/csbroker/apiserver/auth/AuthToken.kt
- src/main/kotlin/io/csbroker/apiserver/auth/AuthTokenProvider.kt
- src/main/kotlin/io/csbroker/apiserver/common/config/QueryDslConfig.kt
- src/main/kotlin/io/csbroker/apiserver/common/config/security/JwtConfig.kt
- src/main/kotlin/io/csbroker/apiserver/common/config/security/SecurityConfig.kt
- src/main/kotlin/io/csbroker/apiserver/common/filter/RequestWrapper.kt
- src/main/kotlin/io/csbroker/apiserver/common/filter/TokenAuthenticationFilter.kt
- src/main/kotlin/io/csbroker/apiserver/common/handler/OAuth2AuthenticationSuccessHandler.kt
- src/main/kotlin/io/csbroker/apiserver/controller/v1/admin/problem/AdminLongProblemController.kt
- src/main/kotlin/io/csbroker/apiserver/controller/v1/admin/problem/AdminMultipleProblemController.kt
- src/main/kotlin/io/csbroker/apiserver/controller/v1/admin/problem/AdminShortProblemController.kt
- src/main/kotlin/io/csbroker/apiserver/repository/problem/StandardAnswerRepository.kt
- src/main/kotlin/io/csbroker/apiserver/service/auth/AuthServiceImpl.kt
- src/main/kotlin/io/csbroker/apiserver/service/problem/AdminLongProblemServiceImpl.kt
- src/main/kotlin/io/csbroker/apiserver/service/problem/AdminMultipleProblemServiceImpl.kt
- src/main/kotlin/io/csbroker/apiserver/service/problem/AdminShortShortProblemServiceImpl.kt
- src/main/kotlin/io/csbroker/apiserver/service/problem/UserAnswerServiceImpl.kt
close: # N/A
- 의존성 목록 : N/A
- 없음
> refactor : unused codes

- src/main/kotlin/io/csbroker/apiserver/controller/v1/common/NotificationController.kt
- src/main/kotlin/io/csbroker/apiserver/dto/notification/NotificationBulkDeleteDto.kt
- src/main/kotlin/io/csbroker/apiserver/model/Notification.kt
- src/main/kotlin/io/csbroker/apiserver/repository/common/NotificationRepository.kt
- src/main/kotlin/io/csbroker/apiserver/service/common/NotificationService.kt
- src/main/kotlin/io/csbroker/apiserver/service/common/NotificationServiceImpl.kt
- src/test/kotlin/io/csbroker/apiserver/controller/v1/common/NotificationControllerTest.kt
close: # N/A
- 의존성 목록 : N/A
- https://www.baeldung.com/spring-jpa-soft-delete <-- 참고 부탁드립니다 🙇
> feat : 알림을 삭제하는 API 추가

- src/main/kotlin/io/csbroker/apiserver/repository/problem/StandardAnswerRepository.kt
- src/main/kotlin/io/csbroker/apiserver/service/problem/AdminLongProblemServiceImpl.kt
close: # N/A
- 의존성 목록 : N/A
- [이 커밋](https://github.com/SW13-Monstera/backend/blob/ec1931c12eb0104a1f91bdab047e57ef93f11f37/src/main/kotlin/io/csbroker/apiserver/service/ProblemServiceImpl.kt)에서 사라진 것 복구입니다.
> fix : standard answer 저장 로직 사라진 것 복구

- src/docs/asciidoc/index.adoc
add remove notification docs
close: #
- 의존성 목록
- 특이 사항 1
- 특이 사항 2
> hotfix : 알림 삭제 Docs 추가

- src/main/kotlin/io/csbroker/apiserver/model/GradingResultAssessment.kt
close: # N/A
- 의존성 목록 : N/A
- generated value를 제대로 지정하지 않으면 버그가 발생하여 추가합니다.
> fix : generated value annotation strategy 지정

- build.gradle.kts
close: # N/A
- 의존성 목록
- kotest-runner-junit5
- kotest-assertions-core
- kotest-extensions-spring
- kotlin에서 많이 쓰는 kotest로 테스트를 작성하기 위한, 의존성 추가입니다.
> chore : add kotest

- src/test/kotlin/io/csbroker/apiserver/controller/v1/admin/problem/AdminProblemSetControllerIntegrationTest.kt
> test : 문제 세트 어드민 API 테스트 코드 추가

- src/test/kotlin/io/csbroker/apiserver/controller/IntegrationTest.kt
- src/test/kotlin/io/csbroker/apiserver/controller/v1/admin/problem/AdminProblemSetControllerIntegrationTest.kt
close: # N/A
- 의존성 목록 : N/A
- 통합테스트에 사용할 함수 및 클래스들입니다. Free to ask!
> feat : 통합테스트에서 사용할 유틸함수 및 기반 클래스 추가

- src/main/kotlin/io/csbroker/apiserver/service/common/NotificationServiceImpl.kt
- src/test/kotlin/io/csbroker/apiserver/service/common/NotificationServiceTest.kt
close: #
- 의존성 목록
- 특이 사항 1
- 특이 사항 2
> test: NotificationServiceTest 추가

- src/test/kotlin/io/csbroker/apiserver/controller/IntegrationTest.kt
close: # N/A
AS-IS 
TO-BE
- N/A
별게 다 되네요;
> test : 테스트 유틸 함수의 쿼리가 syntax highlighting을 적용받을 수 있도록 수정

- .gitignore
- src/main/kotlin/io/csbroker/apiserver/service/problem/LongProblemServiceImpl.kt
- src/test/kotlin/io/csbroker/apiserver/controller/IntegrationTest.kt
- src/test/kotlin/io/csbroker/apiserver/controller/v1/admin/AdminControllerIntegrationTest.kt
- src/test/kotlin/io/csbroker/apiserver/controller/v1/admin/problem/AdminProblemControllerIntegrationTest.kt
- src/test/kotlin/io/csbroker/apiserver/controller/v1/admin/problem/AdminProblemSetControllerIntegrationTest.kt
- src/test/kotlin/io/csbroker/apiserver/controller/v1/problem/LongProblemIntegrationTest.kt
- src/test/kotlin/io/csbroker/apiserver/controller/v1/problem/MultipleProblemIntegrationTest.kt
- src/test/kotlin/io/csbroker/apiserver/controller/v1/problem/ShortProblemIntegrationTest.kt
- src/test/kotlin/io/csbroker/apiserver/service/problem/LongProblemServiceTest.kt
- src/test/kotlin/io/csbroker/apiserver/service/problem/MultipleProblemServiceTest.kt
close: [MSTR-429](https://swm-monstera.atlassian.net/browse/MSTR-429)
- 의존성 목록
- config submodule 업데이트 해주세요
- 테스트일때만 create.sql, delete.sql 생성하고 통합테스트일때만 테이블 초기화를 진행합니다
- https://github.com/SW13-Monstera/backend/commit/50af180d27a40fca6cdb9b163df0b885d2241079
[MSTR-429]: https://swm-monstera.atlassian.net/browse/MSTR-429?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> test : 문제 통합테스트 추가

- src/main/kotlin/io/csbroker/apiserver/controller/v1/common/AuthController.kt
- src/main/kotlin/io/csbroker/apiserver/controller/v1/post/CommentController.kt
- src/main/kotlin/io/csbroker/apiserver/controller/v1/post/PostController.kt
- src/main/kotlin/io/csbroker/apiserver/controller/v1/problem/LongProblemController.kt
- src/main/kotlin/io/csbroker/apiserver/controller/v2/problem/ProblemControllerV2.kt
- src/main/kotlin/io/csbroker/apiserver/controller/v2/problem/request/SubmitLongProblemDto.kt
- src/main/kotlin/io/csbroker/apiserver/dto/user/UserInfoResponseDto.kt
- src/main/kotlin/io/csbroker/apiserver/service/auth/CustomUserDetailsService.kt
- src/main/kotlin/io/csbroker/apiserver/service/post/CommentService.kt
- src/main/kotlin/io/csbroker/apiserver/service/post/CommentServiceImpl.kt
- src/main/kotlin/io/csbroker/apiserver/service/post/PostService.kt
- src/main/kotlin/io/csbroker/apiserver/service/post/PostServiceImpl.kt
- src/main/kotlin/io/csbroker/apiserver/service/problem/CommonProblemService.kt
- src/main/kotlin/io/csbroker/apiserver/service/problem/CommonProblemServiceImpl.kt
- src/main/kotlin/io/csbroker/apiserver/service/problem/LongProblemServiceImpl.kt
- src/test/kotlin/io/csbroker/apiserver/controller/v1/common/AuthControllerTest.kt
- src/test/kotlin/io/csbroker/apiserver/service/problem/CommonProblemServiceTest.kt
- src/test/kotlin/io/csbroker/apiserver/service/problem/LongProblemServiceTest.kt
- src/test/kotlin/io/csbroker/apiserver/service/problem/admin/AdminLongProblemServiceTest.kt
close: #
- 의존성 목록
- 두 가지 궁금한 게 있는데 주석으로 달았고 커멘트로 멘션 드리겠습니다.
> refactor: ArgumentResolver 변경에 따른 사용하지 않는 코드 제거

- src/main/kotlin/io/csbroker/apiserver/common/enums/LikeType.kt
- src/main/kotlin/io/csbroker/apiserver/controller/v1/post/CommentController.kt
- src/main/kotlin/io/csbroker/apiserver/controller/v1/post/PostController.kt
- src/main/kotlin/io/csbroker/apiserver/controller/v1/post/response/CommentResponseDto.kt
- src/main/kotlin/io/csbroker/apiserver/controller/v1/post/response/PostResponseDto.kt
- src/main/kotlin/io/csbroker/apiserver/model/Like.kt
- src/main/kotlin/io/csbroker/apiserver/model/Post.kt
- src/main/kotlin/io/csbroker/apiserver/repository/post/LikeRepository.kt
- src/main/kotlin/io/csbroker/apiserver/repository/post/PostRepository.kt
- src/main/kotlin/io/csbroker/apiserver/service/post/CommentService.kt
- src/main/kotlin/io/csbroker/apiserver/service/post/CommentServiceImpl.kt
- src/main/kotlin/io/csbroker/apiserver/service/post/PostService.kt
- src/main/kotlin/io/csbroker/apiserver/service/post/PostServiceImpl.kt
- src/test/kotlin/io/csbroker/apiserver/controller/v1/post/PostControllerTest.kt
close: #
- 의존성 목록
시간에 쫓겨 테스트 코드를 못 작성했는데 Problem Like까지 이전하고 한번에 테케 짤게욤😂
> feat : 댓글 좋아요 기능 추가

- src/main/kotlin/io/csbroker/apiserver/auth/LoginUserArgumentResolver.kt
close: #
- 의존성 목록
- 특이 사항 1
- 특이 사항 2
> fix : argument resolver에서 잘못된 값으로 user를 찾아오던 버그 수정

- src/main/kotlin/io/csbroker/apiserver/auth/LoginUserArgumentResolver.kt
* fix : argument resolver에서 잘못된 값으로 user를 찾아오던 버그 수정
> Hotfix Release

- src/main/kotlin/io/csbroker/apiserver/service/auth/AuthService.kt
- src/main/kotlin/io/csbroker/apiserver/service/auth/AuthServiceImpl.kt
- src/main/kotlin/io/csbroker/apiserver/service/post/PostService.kt
- src/main/kotlin/io/csbroker/apiserver/service/post/PostServiceImpl.kt
- src/main/kotlin/io/csbroker/apiserver/service/user/UserService.kt
- src/main/kotlin/io/csbroker/apiserver/service/user/UserServiceImpl.kt
- src/test/kotlin/io/csbroker/apiserver/service/AuthServiceTest.kt
- src/test/kotlin/io/csbroker/apiserver/service/UserServiceTest.kt
> chore : remove unused codes

- src/main/kotlin/io/csbroker/apiserver/model/Like.kt
> fix : like 테이블 이름 변경 ( like -> likes )

- src/main/kotlin/io/csbroker/apiserver/auth/LoginUserArgumentResolver.kt
- src/main/kotlin/io/csbroker/apiserver/common/util/AuthUtil.kt
close: # N/A
- 의존성 목록 : N/A
- `as?` 연산자를 통해 안전한 캐스팅을 하여 runCatching을 제거
- 이것을 적용한 함수를 `resolveArgument` 함수에 적용
> refactor : getEmailFromSecurityHolder function

- src/main/kotlin/io/csbroker/apiserver/common/config/security/SecurityConfig.kt
close: #
- 의존성 목록
- 특이 사항 1
- 특이 사항 2
> hotfix : oauth 로그인 오류 수정

- src/main/kotlin/io/csbroker/apiserver/common/config/security/SecurityConfig.kt
close: # N/A
- 의존성 목록 : N/A
- hotfix로 배포나간 것에 대한 dev merge pr입니다~
- 오타였어요.. 흑
> fix : oauth 로그인 오류 수정

- .github/workflows/deploy-prod.yml
- .github/workflows/docs.yml
- .github/workflows/ktlint.yml
- .github/workflows/test.yml
close: #
- 의존성 목록 : N/A
- 버전업!
> chore : github workflow actions version up

- src/main/kotlin/io/csbroker/apiserver/common/handler/GlobalExceptionHandler.kt
close: #
- 의존성 목록
- 특이 사항 1
- 특이 사항 2
> refactor: 로깅에 스택트레이스 추가

- src/main/kotlin/io/csbroker/apiserver/common/handler/GlobalExceptionHandler.kt
close: #
- 의존성 목록
- 특이 사항 1
- 특이 사항 2
> refactor: 로깅에 스택트레이스 추가 (#159)

- src/main/kotlin/io/csbroker/apiserver/common/config/AwsClientConfig.kt
- src/main/kotlin/io/csbroker/apiserver/repository/user/UserRepository.kt
- src/main/kotlin/io/csbroker/apiserver/service/common/MailService.kt
- src/main/kotlin/io/csbroker/apiserver/service/common/S3ServiceImpl.kt
- src/main/kotlin/io/csbroker/apiserver/service/common/SesMailServiceImpl.kt
close: # N/A
- 의존성 목록 : N/A
- 없음
> refactor : aws client

- src/main/kotlin/io/csbroker/apiserver/controller/v2/problem/response/SubmitLongProblemResponseDto.kt
- src/main/kotlin/io/csbroker/apiserver/service/problem/LongProblemServiceImpl.kt
- src/test/kotlin/io/csbroker/apiserver/controller/v1/problem/LongProblemControllerTest.kt
- src/test/kotlin/io/csbroker/apiserver/controller/v1/problem/LongProblemIntegrationTest.kt
close: #
- 의존성 목록
- 특이 사항 1
- 특이 사항 2
> hotfix: 서술형 제출 변수명 변경

- src/main/kotlin/io/csbroker/apiserver/common/util/CookieUtil.kt
- src/main/kotlin/io/csbroker/apiserver/repository/common/OAuth2AuthorizationRequestBasedOnCookieRepository.kt
> refactor : replace deprecated serialization utils
